README.md
No-Country/c6-22 pull request #38
Opened 2022-09-04 18:27 UTC by Briantahiel

Creación del README. Lo puse en inglés no más, porque creo que es más conveniente. Después sigo sumandole cosas. Por favor leerlo y decirme si algo está mal

2022-09-04 18:30 UTC, Briantahiel commented
Falta Piero. Si formó parte lo agrego también

2022-09-04 18:33 UTC, AlejandroWogelman approved these changes

2022-09-06 01:02 UTC, ojedajuanc requested changes

2022-09-06 01:02 UTC, ojedajuanc commented on README.md
> +<h4>TecnoStore comes from the idea of that through the implementation of a web application, we seek to solve the problems of an E-commerce owing to the low sale of its products. Customers will be pro
The idea of this project is to present a modern solution to a wide variety of problems that business owner's might face. This e-commerce project is oriented to retail tech companies that do not have an online presence, allowing them to manage product stock, sales for individual clients who are registered on the website, and to encourage customers loyalty through a newsletter subscription.

2022-09-06 01:27 UTC, ojedajuanc approved these changes

2022-09-06 01:27 UTC, merged